### ISSUE TITLE
Could not resolve dependencies for project org.mal-lang:icslang:jar:0.0.1: Could not find artifact org.mal-lang:corelang:jar:0.1.0 in local-repo

### ISSUE THREAD

**Issue by haofeiyan** [mal-lang/icsLang#2]
Hello there,
I am trying to run icsLang. However I am facing the dependency issue. 
I have run "mvn clean install" under corelang. 
`[INFO] No primary artifact to install, installing attached artifacts instead.
[INFO] Installing /home/haofei/coreLang/pom.xml to /home/haofei/.m2/repository/org/mal-lang/corelang/0.1.0/corelang-0.1.0.pom
[INFO] Installing /home/haofei/coreLang/target/corelang-0.1.0-source.jar to /home/haofei/.m2/repository/org/mal-lang/corelang/0.1.0/corelang-0.1.0-source.jar`
At first, the error is `[ERROR] Failed to execute goal on project icslang: Could not resolve dependencies for project org.mal-lang:icslang:jar:0.0.1: Failure to find org.mal-lang:corelang:jar:0.1.0 in s3://maven.foreseeti.com/release was cached in the local repository, resolution will not be reattempted until the update interval of maven.foreseeti.com-release has elapsed or updates are forced -> [Help 1]`
After I manually added the local repository in pom file:
`<repository>
      <id>local-repo</id>
      <name>Local Repository</name>
      <url>file:///home/haofei/.m2/repository</url>
    </repository>`
The new error is 
`[ERROR] Failed to execute goal on project icslang: Could not resolve dependencies for project org.mal-lang:icslang:jar:0.0.1: Could not find artifact org.mal-lang:corelang:jar:0.1.0 in local-repo (file:///home/haofei/.m2/repository) -> [Help 1]`
Do you know how to fix this?

**Comment by skatsikeas** [comment]
Have you first run `mvn clean install` on the coreLang project? You need to git clone [coreLang](https://github.com/mal-lang/coreLang) and then install it on the maven local repo.

**Comment by andrewbwm** [comment]
I think I had the same problem when I was trying initially and it only got solved when I was able to build the securiCAD package. Maybe there's some issue with how the default package is built.

~I had the corelang-0.1.0.jar in \~/.m2/repository/org/mal-lang/corelang/0.1.0/  so it was installing correctly, it was just that icsLang didn't want to use it for some reason.~

Ok, I think I found the issue, manually copy corelang-0.1.0-source.jar in ~/.m2/repository/org/mal-lang/corelang/0.1.0/ to corelang-0.1.0.jar and see if that works. This isn't a fix it's just a way to identify the issue.  I think the problem is the default package install skips the default-jar step. It seems like the default installation does not trigger generate-code, only the securiCAD profile does. If this is the case, @skatsikeas can probably fix it in the build scripts, Maven is still arcane to me.

If you run mvn clean install you should see that there is no corelang-0.1.0.jar in the target folder, just the corelang-0.1.0-source.jar. So, something is wrong in the build configuration for the default package.

**Comment by haofeiyan** [comment]
> Have you first run `mvn clean install` on the coreLang project? You need to git clone [coreLang](https://github.com/mal-lang/coreLang) and then install it on the maven local repo.

Hello there, yes I did.

**Comment by haofeiyan** [comment]
> I think I had the same problem when I was trying initially and it only got solved when I was able to build the securiCAD package. Maybe there's some issue with how the default package is built.
> 
> ~I had the corelang-0.1.0.jar in ~/.m2/repository/org/mal-lang/corelang/0.1.0/ so it was installing correctly, it was just that icsLang didn't want to use it for some reason.~
> 
> Ok, I think I found the issue, manually copy corelang-0.1.0-source.jar in ~/.m2/repository/org/mal-lang/corelang/0.1.0/ to corelang-0.1.0.jar and see if that works. This isn't a fix it's just a way to identify the issue. I think the problem is the default package install skips the default-jar step. It seems like the default installation does not trigger generate-code, only the securiCAD profile does. If this is the case, @skatsikeas can probably fix it in the build scripts, Maven is still arcane to me.
> 
> If you run mvn clean install you should see that there is no corelang-0.1.0.jar in the target folder, just the corelang-0.1.0-source.jar. So, something is wrong in the build configuration for the default package.

Thanks! It works for me!
